provision out unfilterred maf
oicr-gsi/mutect2Consensus pull request #11
Opened 2024-12-02 15:48 UTC by gavin-peng

2024-12-06 19:20 UTC, gavin-peng commented
Added one commit with two changes:
1, removed genesToKeep from the script 
2, changed output file names: matchedMaf -> somaticMaf; machtedFilteredMaf -> somaticFilteredMaf

question: also change the matchedVepVcf and index name?

2024-12-06 19:36 UTC, lheisler requested changes
changes to the outputs should be labels but ALSO how the files are named.
I think this is an opportunity to also introduce cleaner labels and names, as this workflow is not really in use yet for RUO data release or by CGI for reporting

suggested changes, 
no need to indicate VEP the labels, as these are ALL vep annotated (ie. it is not needed to differentiate).
the final filtered MAFs can be labelled as
tumorFilteredMaf (tumourMaf with normal annotation + filtering)
somaticFilteredMaf (matched/somaticMAF + filtering)

output file names should be simlar, using "Somatic" instead of "Matched".  its hard to figure out exactly what these will look like.  Gavin, can you indicate what extensions you expect to see on each of the output files



    File tumorVcf = variantEffectPredictor.outputVcf[0]
    File tumorVcfIndex = variantEffectPredictor.outputTbi[0]
    File normalVcf = variantEffectPredictor.outputVcf[1]
    File normalVcfIndex = variantEffectPredictor.outputTbi[1]
    File somaticVcf = matchedVep.outputVcf
    File somaticVcfIndex = matchedVep.outputTbi
    File? tumorMaf = variantEffectPredictor.outputMaf[0]
    File? normalMaf = variantEffectPredictor.outputMaf[1]
    File? somaticMaf = matchedVep.outputMaf
    File? tumorFilteredMaf = filterMaf.filteredMaf
    File? somaticFilteredMaf = matchedFilterMaf.filteredMaf

2024-12-06 21:59 UTC, bibilujan commented
Along the lines of Larry's review, can you update the description on https://github.com/oicr-gsi/mutect2Consensus/blob/12665e01de7ac38f1698e44b02e7e517e8398bfe/mutect2Consensus.wdl#L253 to indicate it's from running mutect2 in somatic mode: 
**from**: "maf file of matched tumor and normal before filtering" **update to** "Unfiltered maf file generated from mutect2 run in somatic mode, with matched tumor and normal" 
@lheisler does that make sense? should other descriptions be updated too?

2024-12-09 19:52 UTC, gavin-peng commented
More name and lable changes in new commit, after the change, a list of output file names and suffix (for the test run) is here:

tumorVcf
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22.merged.vep.vcf.gz"

tumorVcfIndex
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22.merged.vep.vcf.gz.tbi"

normalVcf
"/OCT_011152_Ly_R_TS_REV_V2_Panel_VAL_REVTAR23.merged.vep.vcf.gz"

normalVcfIndex
"OCT_011152_Ly_R_TS_REV_V2_Panel_VAL_REVTAR23.merged.vep.vcf.gz.tbi"

tumorMaf
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22.merged.maf.gz"

normalMaf
"/OCT_011152_Ly_R_TS_REV_V2_Panel_VAL_REVTAR23.merged.maf.gz"

tumorfilteredMaf
"/call-filterMaf/execution/OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22_filtered_maf.gz"

somaticVcf
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22_somatic.merged.vep.vcf.gz"

somaticVcfIndex
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22_somatic.merged.vep.vcf.gz.tbi"

somaticMaf
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22_somatic.merged.maf.gz"

somaticFilteredMaf
"OCT_011152_Ct_T_TS_REV_V2_Panel_VAL_REVTAR22_somatic_filtered_maf.gz"

Note the "vep" suffix is genearted from the vep workflow. The "merged" suffix  is from the consenusCruncher workflow, don't know if it's clear to you, rename or remove it?

2024-12-10 18:20 UTC, bibilujan reviewed
minor request on file description.

2024-12-10 18:20 UTC, bibilujan commented on mutect2Consensus.wdl
>            description: "maf file after filtering",
can you update the description of filteredMaf to: "tumour Maf with normal annotation and filtering"

2024-12-11 14:54 UTC, gavin-peng commented on mutect2Consensus.wdl
>            description: "maf file after filtering",
thanks, updated

2024-12-11 15:57 UTC, lheisler commented
file names look good now, not a problem to keep vep in the name if it is just being carried forward.

2024-12-11 15:59 UTC, lheisler approved these changes

2024-12-11 19:39 UTC, bibilujan approved these changes

2024-12-11 20:03 UTC, merged